[tool.poetry]
name = "finance-backend"
version = "0.1.0"
description = "Backend for the Finance Tools Platform"
authors = ["Kuzushi Labs"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
